// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectDiscord(arg1) {
  return window['go']['main']['App']['ConnectDiscord'](arg1);
}

export function SetStatus(arg1) {
  return window['go']['main']['App']['SetStatus'](arg1);
}
