// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConnectDiscord(arg1:string):Promise<main.Return>;

export function SetStatus(arg1:main.Form):Promise<main.Return>;
